server:
  port: 8082

spring:
  application:
    name: inventoryservice

  datasource:
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: orderservice-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false


logging:
  level:
    org.apache.kafka: OFF
    org.springframework.kafka: OFF
    com.rahul: INFO